### ISSUE TITLE
Nice boilerplate, suggest split to three version, one app, one library, one web

### ISSUE THREAD

**Issue by lygstate** [eingress/node-typescript-boilerplate#1]

**Comment by eingress** [comment]
Thanks, although I'm not sure what you're getting at since it is as basic as it gets and purely for node/server projects; it only has eslint/prettier/jest/nodemon set up.

I'm in the process of pushing my react native version if that's what you mean by app, with others to follow. If I'm not understanding correctly then please elaborate.

I'm not going down the 'everything including the kitchen sink' route since that's what everyone else seems to do and it's useless IMO.
